name: CI
on: [push, pull_request]
jobs:
  test-elixir:
    runs-on: ubuntu-latest
    container: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-ubuntu-bionic-${{ matrix.bionic_version }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.7.4
            otp: 19.3.6.13
            bionic_version: 20200403
          - elixir: 1.8.2
            otp: 20.3.8.26
            bionic_version: 20200403
          - elixir: 1.9.4
            otp: 20.3.8.26
            bionic_version: 20200403
          - elixir: 1.10.4
            otp: 21.3.8.17
            bionic_version: 20200630
          - elixir: 1.10.4
            otp: 23.0.3
            bionic_version: 20200630

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: mix test

  test-formatted:
    runs-on: ubuntu-latest
    container: hexpm/elixir:1.10.4-erlang-23.0.3-alpine-3.12.0
    steps:
      - uses: actions/checkout@v2.3.1
      - run: mix format --check-formatted
